module.exports = {
  purge: {
    content: ['./dist/js/*.js'],
    options: {
      safelist: [
        'bg-white',
        'bg-gray-100',
        'bg-gray-200',
        'bg-gray-300',
        'bg-gray-400',
        'bg-gray-500',
        'bg-gray-600',
        'bg-gray-700',
        'bg-gray-800',
        'bg-gray-900',
        'text-white',
        'text-gray-500',
        'text-gray-700',
        'border-white',
        'border-gray-500',
        'border-gray-700',
        'bg-purple-100',
        'bg-purple-200',
        'bg-purple-300',
        'bg-purple-400',
        'bg-purple-500',
        'bg-purple-600',
        'bg-purple-700',
        'bg-purple-800',
        'bg-purple-900',
        'text-purple-500',
        'text-purple-700',
        'border-purple-500',
        'border-purple-700',
        'bg-indigo-100',
        'bg-indigo-200',
        'bg-indigo-300',
        'bg-indigo-400',
        'bg-indigo-500',
        'bg-indigo-600',
        'bg-indigo-700',
        'bg-indigo-800',
        'bg-indigo-900',
        'text-indigo-500',
        'text-indigo-700',
        'border-indigo-500',
        'border-indigo-700',
        'bg-blue-100',
        'bg-blue-200',
        'bg-blue-300',
        'bg-blue-400',
        'bg-blue-500',
        'bg-blue-600',
        'bg-blue-700',
        'bg-blue-800',
        'bg-blue-900',
        'text-blue-500',
        'text-blue-700',
        'border-blue-500',
        'border-blue-700',
        'bg-yellow-100',
        'bg-yellow-200',
        'bg-yellow-300',
        'bg-yellow-400',
        'bg-yellow-500',
        'bg-yellow-600',
        'bg-yellow-700',
        'bg-yellow-800',
        'bg-yellow-900',
        'text-yellow-500',
        'text-yellow-700',
        'border-yellow-500',
        'border-yellow-700',
        'bg-red-100',
        'bg-red-200',
        'bg-red-300',
        'bg-red-400',
        'bg-red-500',
        'bg-red-600',
        'bg-red-700',
        'bg-red-800',
        'bg-red-900',
        'text-red-500',
        'text-red-700',
        'border-red-500',
        'border-red-700'
      ],
      blocklist: [/^debug-/],
      keyframes: true,
      fontFace: true,
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        logo: ['"Major Mono Display"'],
        links: ['"Poiret One"', 'cursive']
      }
    },
  },
  variants: {
    extend: {
    },
  },
  plugins: [],
}
